version: "3"

tasks:
    mock:
        desc: Генерация моков
        cmds:
            - |
                mockgen -source=./gen/go/go-sso/go-sso_grpc.pb.go \
                        -destination=./mocks/mock_auth_client.go \
                        -package=mocks \
                        AuthClient
    generate:
        aliases:
            - gen
        desc: Генерация protobuf файлов
        cmds:
            - >
                protoc -I proto proto/go-sso/go-sso.proto
                --go_out=./gen/go
                --go_opt=paths=source_relative
                --go-grpc_out=./gen/go
                --go-grpc_opt=paths=source_relative
