
version: "3"

tasks:
    generate:
        aliases:
            - gen
        desc: Генерация protobuf файлов
        cmds:
            - >
                protoc -I proto proto/go-sso/go-sso.proto
                --go_out=./gen/go
                --go_opt=paths=source_relative
                --go-grpc_out=./gen/go
                --go-grpc_opt=paths=source_relative
